name: ci

on:
  pull_request:
  push:

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pip install poetry==1.8.4

      - name: Configure Poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install --with dev --no-root --no-interaction

      - name: Ruff check
        run: poetry run ruff check src

      - name: Ruff format
        run: poetry run ruff format src --check
